name: Release Charts

# on:
#   push:
#     branches:
#       - master
on: [push]
env:
  SRC_CHART_PATH: charts/growi
  PUBLISH_BRANCH: gh-pages
  HELM_VERSION: 3.1.0

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart testing (lint)
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.3
          helmv3: ${{ env.HELM_VERSION }}
          command: |
            helm init --client-only
            helm lint ${SRC_CHART_PATH}

  release:
    runs-on: ubuntu-18.04
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Publish chart
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.3
          helmv3: ${{ env.HELM_VERSION }}
          command: |
            # initialize helm and chart dependency
            helm init --client-only
            helm dependency update ${SRC_CHART_PATH}
            
            # Package chart
            PKG_DIR="${HOME}/pkg"
            mkdir ${PKG_DIR}
            helm package ${SRC_CHART_PATH} --destination ${PKG_DIR}
            PKG_NAME=$(basename $(ls ${PKG_DIR}/*.tgz))
            
            # Publish Helm chart to target branch
            GIT_REPOSITORY_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git config user.name ${GITHUB_ACTOR}
            git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
            # git remote set-url origin ${GIT_REPOSITORY_URL}
            # git fetch origin
            # git checkout ${PUBLISH_BRANCH}
            mv ${PKG_DIR}/*.tgz .
            helm repo index .
            git add .
            git commit -m "Publish Helm chart at ${SRC_CHART_PATH} as ${PKG_NAME}"
            # git push origin ${PUBLISH_BRANCH}
            git push -f --set-upstream origin ${PUBLISH_BRANCH}
