name: Release Charts

# on:
#   push:
#     branches:
#       - master
on: [push]
env:
  SRC_CHART_PATH: charts/growi
  HELM_VERSION: 3.1.0

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart testing (lint)
        uses: stefanprodan/kube-tools@v1
        with:
          helmv3: ${{ env.HELM_VERSION }}
          command: |
            helm init --client-only
            helm lint ${SRC_CHART_PATH}

  release:
    runs-on: ubuntu-18.04
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: >
          Create GitHub Release and update index of helm packages in `gh-pages` branch
          which is published as GitHub Pages
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          # This token is required because of an Actions bug
          # (see. https://github.com/marketplace/actions/helm-chart-releaser)
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
