name: Release Charts

# on:
#   push:
#     branches:
#       - master
on: [push]
env:
  SRC_CHART_PATH: charts/growi
  PUBLISH_BRANCH: gh-pages
  HELM_VERSION: 3.1.0

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chart testing (lint)
        uses: stefanprodan/kube-tools@v1
        with:
          helmv3: ${{ env.HELM_VERSION }}
          command: |
            helm init --client-only
            helm lint ${SRC_CHART_PATH}

  release:
    runs-on: ubuntu-18.04
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Package chart
        uses: stefanprodan/kube-tools@v1
        with:
          helmv3: ${{ env.HELM_VERSION }}
          command: |
            helm init --client-only
            helm dependency update ${SRC_CHART_PATH}
            helm package ${SRC_CHART_PATH}
            helm repo index .

      - name: Publish Helm chart to target branch
        run: |
          GIT_REPOSITORY_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git remote set-url origin ${GIT_REPOSITORY_URL}
          git fetch origin
          git checkout ${PUBLISH_BRANCH}
          git add .
          git commit -m "Publish Helm chart at ${SRC_CHART_PATH}"
          git push origin ${PUBLISH_BRANCH}
